### ISSUE TITLE
Golem Color Assignment Seemingly Faulty

### ISSUE THREAD

**Issue by SlvrKnight96** [Azanor/thaumcraft-beta#1423]
I am trying to set up an automatic farm with golems where I have golems set to harvest sugarcane as well as trees that I have set up in the area. Upon noticing that the golems do not replant the trees, I placed 'Use' commands on the ground to make them replant with sapling. Unfortunately it caused the golems that would normally be harvesting my crops to be perpetually trying to plant sapling in that one spot and not do anything else. I tried to fix it by making another golem and set their color so that just that golem will replant sapling, but it was useless. The golems that were not set to that color kept trying to replant sapling despite having the wrong color. When I changed them to a different color, it seemed to work, but that seems like a bug to me. Also, the golems take a long time to respond when the crops are growing and will sit there for a long time before attending to the crops.

**Comment by Minamikaze392** [comment]
I'm using beta 23 and the coloring issue happens to me too. I haven't check whether it is already fixed in beta 24 though.
I have an auto farm with several seals(harvest, collect, use for drawer controller) colored red. Occasionally my uncolored golem who is working at the mob grinder will run to collect the crops dropped on the ground :/

For the 'Use' seal issue you have, try to put the seal on the block _above_ the dirt, and check the 'click empty air' option. Then see if it works properly.

**Comment by Azanor** [comment]
'Uncolored' golems count as all colors and will do all jobs.

**Comment by Minamikaze392** [comment]
@Azanor Oooops I didn't know that LOL, thanks!

**Comment by Azanor** [comment]
@SlvrKnight96 
If a golem had been assigned a task before its color was changed, it may still continue trying to complete that task till it eventually times out. 
If you set your harvest seal area too large it will take a long time to check if all the blocks have grown. To prevent lag the seal only checks a few blocks at a time so for large areas it might take a while for it to reach a crop that has grown.

**Comment by SlvrKnight96** [comment]
@Azanor 
Thanks for the tip! I think I understand the problem now.
