### ISSUE TITLE
Thaumcraft 6 not compatible with llibrary

### ISSUE THREAD

**Issue by Kaito1234** [Azanor/thaumcraft-beta#1497]

**Comment by NickelHub** [comment]
You should explain, what you mean by "not coompatible". 
Do you suffer from crashes or graphigal issues?

**Comment by Kaito1234** [comment]
> You should explain, what you mean by "not coompatible".
> Do you suffer from crashes or graphigal issues?

yeah, sorry

here is the report:
[crash-2018-10-12_12.47.26-client.txt](https://github.com/Azanor/thaumcraft-beta/files/2472904/crash-2018-10-12_12.47.26-client.txt)

**Comment by Kaito1234** [comment]
I fixed my problem, it was a problem with new forge

**Comment by NickelHub** [comment]
Just press the close button. :D

**Comment by NickelHub** [comment]
Same as https://github.com/Azanor/thaumcraft-beta/issues/1473.

**Comment by CookieHunteRRR** [comment]
So this bug still not fixed? Doesn't work for me too, even at forge versions lower than 2767

**Comment by NickelHub** [comment]
The new Thaumcraft version hasn't been released yet.

**Comment by CookieHunteRRR** [comment]
I don't understand why it doesn't work with 2766 though

**Comment by NickelHub** [comment]
You can use Thaumcraft with Forge 2765.
