### ISSUE TITLE
Can't unlock Golemancy (BETA 3)

### ISSUE THREAD

**Issue by Pisces24** [Azanor/thaumcraft-beta#261]
When I open the golemancy tab in the thaumonomicon and hover over the beginning icon it is called "research.BASEGOLEMANCY.title". If I open the entry it shows the title as "research.BASEGOLEMANCY.title" and instead of an entry it just says "research.BASEGOLEMANCY.stage1". 
I have done the tasks to unlock the golemancy tab (incl scanning an iron golem). I cannot make anything else in the golemancy tab because it says I am missing the required research.
I can still add progress to golemancy through the theory table.

Is this a bug or have I missed something? Thanks :)

Edit: I have completed the hedge alchemy tab but I still cannot see the materials branch or unlock clockwork minds. Can anyone else help?

**Comment by alfa38** [comment]
it's BETA 4 about a week i guess already and this was fixed

**Comment by Goof245** [comment]
Nothing about this changed in beta4, but if you mouseover unobtainable researches in beta4 it will tell you what you are missing to unlock that research.

**Comment by taggedjc** [comment]
You are missing Hedge Alchemy in the Alchemy Tab, I believe.  You need to know how to make magical wax.

**Comment by Pisces24** [comment]
I have completed the hedge alchemy tab but I still cannot see the materials branch or unlock clockwork minds. Can anyone else help?

**Comment by Goof245** [comment]
Mouseover it. In BETA4 the Thaumonomicon basically spoonfeeds you...
![2018-02-14_14 25 36](https://user-images.githubusercontent.com/3851003/36187771-22bf0378-1193-11e8-9ea1-41bfa55b5b8b.png)
